name: Benchmarks

on:
  push:
    branches:
      - main
jobs:
  detray_benchmark_job:
    if: github.repository == 'beomki-yeo/traccc-trigger-test22'
    runs-on: ubuntu-latest
    steps:
      - run: >
          curl -X POST --fail
          -F token=${{ secrets.TRACCC_BENCHMARK_TRIGGER_TOKEN }}
          -F ref=master
          --form variables[MERGE_TIME]="$(date '+%Y-%m-%d_%H:%M:%S')"
          --form variables[SOURCE_SHA]="${{ github.sha }}"
          https://gitlab.cern.ch/api/v4/projects/190887/trigger/pipeline
